server:
    host: 127.0.0.1
    port: 8011
    path: /koi-net
koi_net:
    node_name: github-processor
    node_rid: orn:koi-net.node:github-processor+0bf78f28-9f56-4d31-8377-a33f49a0828e
    node_profile:
        base_url: http://github-processor:8011/koi-net
        node_type: FULL
        provides:
            event: []
            state: []
    cache_directory_path: .koi/github-processor/cache
    event_queues_path: .koi/github-processor/queues.json
    first_contact: http://coordinator:8080/koi-net
index_db_path: .koi/github-processor/index.db
env:
    github_token: GITHUB_TOKEN
